"""markdown

Revision ID: 46780807d831
Revises: b02996f454f3
Create Date: 2021-05-10 23:22:31.031176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46780807d831'
down_revision = 'b02996f454f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
